apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-1
  name: flask-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app-1
    spec:
      containers:
      #- image: aspadhi/flask-app-1:latest
      - image: aspadhi/{{IMAGE_NAME}}
        name: flask-app-1
        ports:
        - containerPort: 8000
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-1
  name: flask-app-1
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: flask-app-1
status:
  loadBalancer: {}

